### ISSUE TITLE
Fix "Load file" modal

### ISSUE THREAD

**Issue by itsharshag** [itsharshag/devkit#2]
After clicking on the "Load file" modal, there is no way to exit the modal. The only options are to refresh the page or to use an actual file.

Need to explore this issue and fix it. Also, need to check if we are using the modal component of next-ui library or not.

**Comment by staranbeer** [comment]
hey! i have solved this issue and the modal is from blueprintjs.

**Comment by itsharshag** [comment]
The following PR (by @staranbeer): https://github.com/itsharshag/devkit/pull/5 fixes this issue. Thanks again for the contribution!
